### PR TITLE
Added KMZ file, parser for it, and animation logic for little Xinlu icon

### PR DESCRIPTION
**Pull request by hamzakubba**

### CODE REVIEW

**Comment by hamzakubba** [comment]
animatedxinlu

**Comment by hamzakubba** [comment]
animatedxinlu2
Now with smooth zoom!

**Comment by xinluh** [comment]
@hamzakubba doesn't seem to work when deployed :/

**Comment by hamzakubba** [comment]
It does for me on the preview site, but also does take a good 3-5 seconds to do so (to download, unzip and process the kmz file). I'll make it so you have a click a button to start the animation so it starts in the same state as it does now, and the animation can be played by the user (that way the delay is hopefully expected).

**Comment by hamzakubba** [comment]
animatedxinlu3
Alright, no longer blocks loading at the start!

**Comment by xinluh** [comment]
Thanks @hamzakubba this gives me a good crack up :D

**Comment by hamzakubba** [comment]
You're welcome! It was fun to do, and I figured this would give people a little bit more sense of scale as they trace your epic journey! :)

**Pull request merged**
